---
jobs:
- name: simple
  plan:
  - task: simple-task
    config:
      platform: darwin
      run:
        path: /bin/sh
        args:
        - -c
        - |
          echo "testing..."
#          start go server here
#          install yarn packages
#          yarn serve
